### ISSUE TITLE
Example fails with Python3.4, Anaconda3.

### ISSUE THREAD

**Issue by mr664** [endrebak/snpflip#9]
This issue arose whilst debugging another, I'm raising this one specifically to determine whether Python3.4 or Anaconda3 compatibility is the issue.

The command I'm using to run the example dataset is:
```snpflip --fasta-genome=example.fa --bim-file=example.bim```

Which returns the following error message:

```
Traceback (most recent call last):
  File "/home/matt/anaconda3/lib/python3.4/site-packages/pandas/core/ops.py", line 469, in na_op
    raise_on_error=True, **eval_kwargs)
  File "/home/matt/anaconda3/lib/python3.4/site-packages/pandas/computation/expressions.py", line 218, in evaluate
    **eval_kwargs)
  File "/home/matt/anaconda3/lib/python3.4/site-packages/pandas/computation/expressions.py", line 129, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b, raise_on_error)
  File "/home/matt/anaconda3/lib/python3.4/site-packages/pandas/computation/expressions.py", line 71, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for -: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matt/anaconda3/bin/snpflip", line 42, in <module>
    snp_table = create_snp_table(args["--bim-file"], args["--fasta-genome"])
  File "/home/matt/anaconda3/lib/python3.4/site-packages/snp_flip/table.py", line 9, in create_snp_table
    bim_table = read_bim_file(bim_file)
  File "/home/matt/anaconda3/lib/python3.4/site-packages/snp_flip/bim_file.py", line 13, in read_bim_file
    bim_table["position"] = bim_table.position - 1
  File "/home/matt/anaconda3/lib/python3.4/site-packages/pandas/core/ops.py", line 532, in wrapper
    return left._constructor(wrap_results(na_op(lvalues, rvalues)),
  File "/home/matt/anaconda3/lib/python3.4/site-packages/pandas/core/ops.py", line 479, in na_op
    result[mask] = op(x[mask], y)
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

**Comment by endrebak** [comment]
Thanks, will look into it straight away.

**Comment by endrebak** [comment]
Not able to reproduce on `python 3.5`. I'm also using anaconda.

The error message says that it interprets the `position` column from the `bim` file as a string, and that it cannot deduct the number one from a string. I believe the problem is that your version of pandas does not autodetect that the third column in this file is an int:

https://github.com/endrebak/snpflip/blob/master/examples/example.bim 

You might want to try updating all dependencies of snpflip (might take some time as it will install `pandas 0.17.1`) with the following command:

```
pip install -U --no-cache-dir snpflip
```

If this does not work, I will manually cast the column to an int.

**Comment by mr664** [comment]
Thanks for the quick response, I reinstalled the relevant programs & scripts only to find that I had (embarrassingly) been using the wrong example files. Replacing these with the correct copies resolves this issue. That said, my initial bug remains so I'll open that as a new issue.

**Comment by endrebak** [comment]
Thanks, I'll look more into it then.
